# fly.toml file generated for bizboost-admin on 2023-03-30T23:40:27+07:00

app = "bizboost-admin"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[deploy]
  release_command = "python manage.py migrate"

[env]
  R2_ACCOUNT_ID = "581dcf5c7d2c8c844c07ea8edd8fa999"
  R2_ACCESS_KEY_ID = ""
  R2_ACCESS_KEY_SECRET = ""
  R2_THUMBNAIL_BUCKET = "thumbnails"
  R2_TRAILER_BUCKET = "trailers"
  R2_VIDEO_BUCKET = "videos"
  PORT = "8000"
  DB_PORT=5432
  DB_HOST="upscale-db.flycast"
  DB_USER="bizboost_admin"
  DB_PASSWORD="howJ0tq5mLJvhlC"
  DB_NAME="upscale"
  DEBUG="False"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
